import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from '@/app/ui/styles/Layout.module.css';
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react';
import Cookies from 'js-cookie';
import SessionProvider  from "./ui/components/SessionProvider"
import { getServerSession } from "next-auth";
import MenuBar from '@/app/ui/components/menubar';

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();

  return (

    <html>
    <body>
    <div className={styles.container}>
      <header className={styles.header}>
         Welcome to assets
      </header>

      <SessionProvider session={session}>
      <MenuBar/>  
      <main className={styles.main}>{children}</main>
      </SessionProvider>

      <footer className={styles.footer}>
        &copy; {new Date().getFullYear()} HeavyDuty Software
      </footer>
    </div>
    </body>
    </html>


    
  )
}
