'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from '@/app/ui/styles/Layout.module.css';
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react';
import Cookies from 'js-cookie';

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html>
    <body>
    <div className={styles.container}>
      <header className={styles.header}>
         Welcome to assets
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        &copy; {new Date().getFullYear()} Your App Footer
      </footer>
    </div>
    </body>
    </html>


    
  )
}
